name: Deploy Release
on: 
  push:
    tags:
    - 'v*'
    - '!v*-alpha'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@master
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
  deploy_to_heroku:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12 
      with:
        heroku_api_key: ${{secrets.heroku_api_key}}
        heroku_app_name: vttpminiproj-book
        heroku_email: ${{secrets.MY_EMAIL}}
        branch: ${{ github.ref_name }}