name: Deploy Release
on: 
  push:
    tags:
    - 'v*'
    - '!v*-alpha'
jobs:
  deploy_to_heroku:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12 
      with:
        heroku_api_key: ${{secrets.heroku_api_key}}
        heroku_app_name: vttpminiproj-book
        heroku_email: ${{secrets.MY_EMAIL}}
        branch: ${{ github.ref_name }}